apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nojsgame-ekh7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nojsgame-ekh7
    app.kubernetes.io/part-of: my-app
  name: nojsgame-ekh7
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nojsgame-ekh7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nojsgame-ekh7
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:mdsaud-tenant-nojsgame-ekh7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
