apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: pacman-w3el
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:mdsaud-tenant-pacman-w3el
        name: my-nodejs
        resources: {}
status: {}
